In [1]:
import pandas as pd
import ast
import os

In [8]:
def data_split6(df):
    df['drug_adjacent'] = df['drug_adjacent'].apply(ast.literal_eval)
    df['symptom_adjacent'] = df['symptom_adjacent'].apply(ast.literal_eval)
    df1 = data[['report_id', 'standard_drug', 'drug_adjacent']].drop_duplicates(subset=['report_id', 'standard_drug']).explode('drug_adjacent')
    df2 = data[['report_id', 'standard_symptom', 'symptom_adjacent']].drop_duplicates(subset=['report_id', 'standard_symptom']).explode('symptom_adjacent')
    df3 = data[['report_id', 'standard_drug', 'standard_symptom', 'symptom_adjacent']].drop_duplicates(subset=['report_id', 'standard_drug', 'standard_symptom']).explode('symptom_adjacent')
    df4 = df2
    df5 = data[['report_id', 'standard_drug', 'drug_adjacent']].drop_duplicates(subset=['report_id', 'standard_drug'])
    df6 = df2

    df1.to_csv('./dfs_llm/df1.csv', index=False)
    df2.to_csv('./dfs_llm/df2.csv', index=False)
    df3.to_csv('./dfs_llm/df3.csv', index=False)
    df4.to_csv('./dfs_llm/df4.csv', index=False)
    df5.to_csv('./dfs_llm/df5.csv', index=False)
    df6.to_csv('./dfs_llm/df6.csv', index=False)

In [9]:
data = pd.read_csv('final_data.csv')

os.makedirs("./dfs_llm", exist_ok=True)

data_split6(data)

In [5]:
print(os.getcwd())

/users/PAS2015/pingwei821/model1/consolidated_pipeline/irAE_model_202507/external_validation/demo/irAE_preprocessing/data

In [18]:
df2

,report_id,standard_symptom,symptom_adjacent
0,R001,Diarrhea,Patient with metastatic melanoma currently rec...
1,R001,Fatigue,Patient with metastatic melanoma currently rec...
2,R001,Rash,Patient with metastatic melanoma currently rec...
3,R002,Colitis,The patient has stage IV non-small cell lung c...
4,R002,Diarrhea,The patient has stage IV non-small cell lung c...
5,R002,Fatigue,The patient has stage IV non-small cell lung c...
6,R003,Pruritus,History of renal cell carcinoma on combination...
7,R003,Rash,History of renal cell carcinoma on combination...
8,R003,Shortness of Breath,History of renal cell carcinoma on combination...
12,R006,Arthralgia,Melanoma patient on pembrolizumab reports no n...
13,R006,Diarrhea,Melanoma patient on pembrolizumab reports no n...
14,R006,Rash,Melanoma patient on pembrolizumab reports no n...
15,R007,Arthritis,Stage IV small cell lung cancer patient receiv...
16,R007,Rheumatology,Stage IV small cell lung cancer patient receiv...
17,R007,Stiffness,Stage IV small cell lung cancer patient receiv...
18,R008,Adrenal Insufficiency,Renal cell carcinoma on ipilimumab monotherapy...
19,R008,Dizziness,Renal cell carcinoma on ipilimumab monotherapy...
20,R008,Fatigue,Renal cell carcinoma on ipilimumab monotherapy...
21,R009,Erythema,Metastatic melanoma on atezolizumab. Mild <sym...
22,R009,Rash,Metastatic melanoma on atezolizumab. Mild eryt...

In [19]:
df3

,report_id,standard_drug,standard_symptom,symptom_adjacent
0,R001,nivolumab,Diarrhea,Patient with metastatic melanoma currently rec...
1,R001,nivolumab,Fatigue,Patient with metastatic melanoma currently rec...
2,R001,nivolumab,Rash,Patient with metastatic melanoma currently rec...
3,R002,pembrolizumab,Colitis,The patient has stage IV non-small cell lung c...
4,R002,pembrolizumab,Diarrhea,The patient has stage IV non-small cell lung c...
5,R002,pembrolizumab,Fatigue,The patient has stage IV non-small cell lung c...
6,R003,ipilimumab,Pruritus,History of renal cell carcinoma on combination...
7,R003,ipilimumab,Rash,History of renal cell carcinoma on combination...
8,R003,ipilimumab,Shortness of Breath,History of renal cell carcinoma on combination...
9,R003,nivolumab,Pruritus,History of renal cell carcinoma on combination...
10,R003,nivolumab,Rash,History of renal cell carcinoma on combination...
11,R003,nivolumab,Shortness of Breath,History of renal cell carcinoma on combination...
12,R006,pembrolizumab,Arthralgia,Melanoma patient on pembrolizumab reports no n...
13,R006,pembrolizumab,Diarrhea,Melanoma patient on pembrolizumab reports no n...
14,R006,pembrolizumab,Rash,Melanoma patient on pembrolizumab reports no n...
15,R007,nivolumab,Arthritis,Stage IV small cell lung cancer patient receiv...
16,R007,nivolumab,Rheumatology,Stage IV small cell lung cancer patient receiv...
17,R007,nivolumab,Stiffness,Stage IV small cell lung cancer patient receiv...
18,R008,ipilimumab,Adrenal Insufficiency,Renal cell carcinoma on ipilimumab monotherapy...
19,R008,ipilimumab,Dizziness,Renal cell carcinoma on ipilimumab monotherapy...
20,R008,ipilimumab,Fatigue,Renal cell carcinoma on ipilimumab monotherapy...
21,R009,Atezolizumab,Erythema,Metastatic melanoma on atezolizumab. Mild <sym...
22,R009,Atezolizumab,Rash,Metastatic melanoma on atezolizumab. Mild eryt...

In [20]:
df5

   report_id  standard_drug                                      drug_adjacent
0       R001      nivolumab  [Patient with metastatic melanoma currently re...
3       R002  pembrolizumab  [The patient has stage IV non-small cell lung ...
6       R003     ipilimumab  [History of renal cell carcinoma on combinatio...
9       R003      nivolumab  [History of renal cell carcinoma on combinatio...
12      R006  pembrolizumab  [Melanoma patient on <drug> PEMBROLIZUMAB </dr...
15      R007      nivolumab  [Stage IV small cell lung cancer patient recei...
18      R008     ipilimumab  [Renal cell carcinoma on <drug> IPILIMUMAB </d...
21      R009   Atezolizumab  [Metastatic melanoma on <drug> Atezolizumab </...